import { Metadata } from 'next';
import React from 'react'
import TermsOfUse from './components/TermOfUse';
export const metadata: Metadata = {
    title: "ShareNest | term-of-use",
    description: "Generated by create ShareNest",
  };
const TermOfUsePage = () => {
  return (
    <div>
<TermsOfUse/>

    </div>
  )
}

export default TermOfUsePage