import { DashboardLayout } from '@/components/Dashboard/DashboardLayout'
import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "ShareNest App || dashboard",
  description: "Generated by create next app",
};
const DashboardLayoutNew = ({children}:{children:React.ReactNode}) => {
  return (
    <div>
      
       <DashboardLayout>
        {children}
       </DashboardLayout>
    </div>
  )
}

export default DashboardLayoutNew