import React from "react";

import { Metadata } from "next";
import Register from "./components/Register";

export const metadata: Metadata = {
  title: "ShareNest | register",
  description: "Generated by create ShareNest",
};

const RegisterPage = () => {
  return (
    <div>
      <Register />
    </div>
  );
};

export default RegisterPage;
