import type { Metadata } from "next";

import "./globals.css";


import { Poppins as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/lib/providers/theme-provider";
const fontSans=FontSans({
  subsets:["latin"],
  weight:['100','200','300','400','500','600','700'],
  variable:"--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning>
      <body className={cn(
        'min-h-screen bg-background font-sans antialiased', fontSans.variable
      )}>
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
