import React from 'react'
import FlatsShow from './components/FlatsShow'
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: "ShareNest | Flats",
  description: "Generated by create ShareNest",
};

const ShowFlat = () => {
  return (
    <div>
      <FlatsShow/>
    </div>
  )
}

export default ShowFlat