import React from 'react'
import ResetPassword from './components/ResetPassword'
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: "ShareNest || Reset-password",
  description: "Generated by create ShareNest",
};
const ResetPasswordPage = () => {
  return (
    <div>
      <ResetPassword/>
    </div>
  )
}

export default ResetPasswordPage