import React from 'react'
import AboutUs from './components/AboutUs'
import { Metadata } from 'next';




export const metadata: Metadata = {
  title: "ShareNest | about us",
  description: "Generated by create ShareNest",
};

const AboutUsPage = () => {

  return (
    <div>
      <AboutUs/>
    </div>
  )
}

export default AboutUsPage