
import React from 'react'
import Login from './components/Login'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "ShareNest | Login",
  description: "Generated by create ShareNest",
};

const LoginPage = () => {
  return (
    <div>
      <Login/>
    </div>
  )
}

export default LoginPage
