import { Metadata } from "next";
import DetailsCard from "./components/DetailsCard"


type TProps={
    params:{
        flatId:string
    }
}
export const metadata: Metadata = {
  title: "shareNest || Flat Details",
  description: "Generated by ShareNest",
};
const FlatDetailsPage = ({params}:TProps) => {
  const id= params.flatId
 
 
  return (
    <div>
      <DetailsCard id={id}/>
    </div>
  )
}

export default FlatDetailsPage